export const appRoutes = {
  LOGIN: '/login',
  HOME: '/',
  DASHBOARD: '/dashboard',
  INSPECTIONS: '/inspections',
  INSPECTION_DETAIL: '/inspections/:id',
  REPORTS: '/reports',
  // Concepts
  CONCEPTS_USE_STATE: '/concepts/use-state',
  CONCEPTS_USE_EFFECT: '/concepts/use-effect',
  CONCEPTS_USE_REF: '/concepts/use-ref',
  CONCEPTS_USE_MEMO_CALLBACK: '/concepts/use-memo-callback',
  CONCEPTS_STABLE_REFERENCES: '/concepts/stable-references',
  CONCEPTS_USE_REDUCER: '/concepts/use-reducer',
  CONCEPTS_USE_TRANSITION: '/concepts/use-transition',
  CONCEPTS_CONTEXT_API: '/concepts/context-api',
  CONCEPTS_CUSTOM_HOOKS: '/concepts/custom-hooks',
  CONCEPTS_REDUX: '/concepts/redux',
  CONCEPTS_STYLED_COMPONENTS: '/concepts/styled-components',
  // Design Patterns
  PATTERNS_HOOKS: '/patterns/hooks',
  PATTERNS_COMPOUND: '/patterns/compound',
  PATTERNS_CONTAINER_PRESENTATIONAL: '/patterns/container-presentational',
  PATTERNS_RENDER_PROPS: '/patterns/render-props',
  PATTERNS_AI_UI: '/patterns/ai-ui',
  // Forms
  FORMS_CONTROLLED: '/forms/controlled',
  FORMS_UNCONTROLLED: '/forms/uncontrolled',
  FORMS_HOOK_FORM: '/forms/react-hook-form',
};
